- platform: template
  switches:
    ac2cool:
      friendly_name: Cool2
      value_template: "{{ is_state_attr('climate.trane2_cooling_1', 'operation_mode', 'Cool') }}"
      turn_on:
        service: climate.set_operation_mode
        entity_id: climate.trane2_cooling_1
        data_template:
          operation_mode: Cool
      turn_off:
        service: climate.set_operation_mode
        entity_id: climate.trane2_cooling_1
        data_template:
          operation_mode: Auto
    ac2heat:
      friendly_name: Heat2
      value_template: "{{ is_state_attr('climate.trane2_cooling_1', 'operation_mode', 'Heat') }}"
      turn_on:
        service: climate.set_operation_mode
        entity_id: climate.trane2_cooling_1
        data_template:
          operation_mode: Heat
      turn_off:
        service: climate.set_operation_mode
        entity_id: climate.trane2_cooling_1
        data_template:
          operation_mode: Auto
    ac2fan:
      friendly_name: Fan2
      value_template: "{{ is_state_attr('climate.trane2_cooling_1', 'fan_mode', 'On Low') }}"
      turn_on:
        service: climate.set_fan_mode
        entity_id: climate.trane2_cooling_1
        data_template:
          fan_mode: On Low
      turn_off:
        service: climate.set_fan_mode
        entity_id: climate.trane2_cooling_1
        data_template:
          fan_mode: Auto Low
