- platform: template
  switches:
    ac3cool:
      friendly_name: Cool3
      value_template: "{{ is_state_attr('climate.trane3_cooling_1', 'operation_mode', 'Cool') }}"
      turn_on:
        service: climate.set_operation_mode
        entity_id: climate.trane3_cooling_1
        data_template:
          operation_mode: Cool
      turn_off:
        service: climate.set_operation_mode
        entity_id: climate.trane3_cooling_1
        data_template:
          operation_mode: Auto
    ac3heat:
      friendly_name: Heat3
      value_template: "{{ is_state_attr('climate.trane3_cooling_1', 'operation_mode', 'Heat') }}"
      turn_on:
        service: climate.set_operation_mode
        entity_id: climate.trane3_cooling_1
        data_template:
          operation_mode: Heat
      turn_off:
        service: climate.set_operation_mode
        entity_id: climate.trane3_cooling_1
        data_template:
          operation_mode: Auto
    ac3fan:
      friendly_name: Fan3
      value_template: "{{ is_state_attr('climate.trane3_cooling_1', 'fan_mode', 'On Low') }}"
      turn_on:
        service: climate.set_fan_mode
        entity_id: climate.trane3_cooling_1
        data_template:
          fan_mode: On Low
      turn_off:
        service: climate.set_fan_mode
        entity_id: climate.trane3_cooling_1
        data_template:
          fan_mode: Auto Low
