- platform: mqtt
  name: 'esp_1668c4_relayset'
  command_topic: 'home/ESP_1668C4/relay/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'esp_90b322_relayset'
  command_topic: 'home/ESP_90B322/relay/set'
  payload_on: 'ON'
  payload_off: 'OFF'
- platform: mqtt
  name: 'esp_90b322_relay2set'
  command_topic: 'home/ESP_90B322/relay2/set'
  payload_on: 'ON'
  payload_off: 'OFF'
