- platform: template
  switches:
    garage_clicker:
      value_template: "{{ is_state('sensor.esp_1668c4_relay', '1.0') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.esp_1668c4_relayset
      turn_off:
        service: switch.turn_off
        entity_id: switch.esp_1668c4_relayset
 
