- id: '1'
  alias: sunset
  trigger:
  - event: sunset
    offset: -00:40:00
    platform: sun
  action:
  - service: script.trane1_normal
  - service: script.trane3_normal
  - data:
      entity_id: switch.geplug1_switch
    service: switch.turn_on
- id: '2'
  alias: bedtime
  trigger:
  - at: '22:30:00'
    platform: time
  action:
  - data: {}
    service: script.trane2_normal
  - data:
      entity_id: switch.geplug1_switch
    service: switch.turn_off
- id: '1535975204294'
  alias: weather
  trigger:
  - event_data: {}
    event_type: feedreader
    platform: event
  condition: []
  action:
  - alias: ''
    data_template:
      message: '{{ trigger.event.data.summary }} {{ trigger.event.data.id }}'
      title: '{{ trigger.event.data.title }}'
    service: persistent_notification.create
- id: '1542323971038'
  alias: sunrise
  trigger: []
  condition: []
  action: []
- id: '1544902602441'
  alias: burglar
  trigger:
  - entity_id: sensor.esp_90b322_motion
    platform: state
    to: 'ON'
  condition:
  - condition: state
    entity_id: input_boolean.guard_away
    state: 'on'
  action:
  - data:
      message: Motion detected in family room
    service: notify.pushbullet
  - data:
      entity_id: camera.cam121
      filename: /config/camera/family.jpg
    service: camera.snapshot
  - data:
      data:
        file: /config/camera/family.jpg
      message: Family camera
    service: notify.pushbullet
- id: '1545048605883'
  alias: reboot
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: 'on'
      topic: home/status
    service: mqtt.publish
- id: '1575200189786'
  alias: noon
  description: ''
  trigger:
  - at: '12:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.guard_away
    state: 'on'
  action:
  - service: script.house_report
- id: '1575593360940'
  alias: curfew
  description: ''
  trigger:
  - at: '2:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id,: switch.geplug1_switch
    service: switch.turn_off
- id: '1582205147315'
  alias: guard_away
  description: ''
  trigger:
  - entity_id: input_boolean.guard_away
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: script.all_good
