- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:05:00'
  action:
    service: switch.turn_on
    entity_id: switch.dlink

- alias: BedTime
  trigger:
    platform: time
    after: '22:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.dlink

- alias: Midnight
  trigger:
    platform: time
    after: '00:00:00'
  action:
    service: countdown.update

- alias: GarageLeftOpen
  trigger:
    platform: state
    entity_id: device_tracker.padre_s6
    state: 'not_home'
  condition:
    condition: state
    entity_id: sensor.garage_door
    state: 'open'
  action:
    service: notify.twitter
    data:
      message: Dejastes el garage abierto

- alias: HTPCOff
  trigger:
    platform: state
    entity_id: switch.htpc
    state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.htpc

- alias: GarageOff
  trigger:
    platform: state
    entity_id: switch.ge_45603_plugin_appliance_module_switch_3_0
    state: 'on'
  action:
    - delay:
        seconds: 5
    - service: switch.turn_off
      data:
        entity_id: switch.ge_45603_plugin_appliance_module_switch_3_0

- alias: Cool1Target
  trigger:
    platform: state
    entity_id: input_select.cool1target
  action:
    service: climate.set_temperature
    entity_id: climate.trane_model_tzemt400bb32maa_cooling_1_2_2
    data_template:
      temperature: "{{ states('input_select.cool1target') }}"

- alias: Heat1Target
  trigger:
    platform: state
    entity_id: input_select.heat1target
  action:
    service: climate.set_temperature
    entity_id: climate.trane_model_tzemt400bb32maa_heating_1_2_1
    data_template:
      temperature: "{{ states('input_select.heat1target') }}"

- alias: Cool2Target
  trigger:
    platform: state
    entity_id: input_select.cool2target
  action:
    service: climate.set_temperature
    entity_id: climate.trane_model_tzemt400bb32maa_cooling_1_4_2
    data_template:
      temperature: "{{ states('input_select.cool2target') }}"

- alias: Heat2Target
  trigger:
    platform: state
    entity_id: input_select.heat2target
  action:
    service: climate.set_temperature
    entity_id: climate.trane_model_tzemt400bb32maa_heating_1_4_1
    data_template:
      temperature: "{{ states('input_select.heat2target') }}"

- alias: Cool3Target
  trigger:
    platform: state
    entity_id: input_select.cool3target
  action:
    service: climate.set_temperature
    entity_id: climate.trane_model_tzemt400bb32maa_cooling_1_5_2
    data_template:
      temperature: "{{ states('input_select.cool3target') }}"

- alias: Heat3Target
  trigger:
    platform: state
    entity_id: input_select.heat3target
  action:
    service: climate.set_temperature
    entity_id: climate.trane_model_tzemt400bb32maa_heating_1_5_1
    data_template:
      temperature: "{{ states('input_select.heat3target') }}"


