homeassistant: !include home.yaml
frontend:
history:
logbook:
logger: !include logger.yaml
recorder:
  purge_days: 8
sun:
emulated_hue: !include hue.yaml
mqtt: !include mqtt.yaml
device_tracker: !include owntracks.yaml
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
light: !include_dir_merge_list lights
notify: !include notify.yaml
group: !include groups.yaml
automation: !include_dir_list automation
input_select: !include selections.yaml
# weblink: !include weblinks.yaml
zwave: !include zwave.yaml
climate: !include climate.yaml
media_player: !include vlc.yaml
tts: !include tts.yaml
script: !include_dir_named scripts
shell_command: !include shellcmds.yaml

# Custom Components
hola:
  - name: ricardo
# panel_custom: !include react.yaml
countdown:
