homeassistant: !include home.yaml
frontend:
hassio:
config:
http: !include http.yaml
#map:
history:
#logbook:
logger: !include logger.yaml
recorder:
sun:
mqtt: !include mqtt.yaml
emulated_hue: !include hue.yaml
device_tracker: !include device_trackers.yaml
zone: !include zones.yaml
input_select: !include select.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
light: !include_dir_merge_list lights
notify: !include notify.yaml
group: !include groups.yaml
automation: !include automations.yaml
alert: !include alerts.yaml
zwave: !include zwave.yaml
climate: !include climate.yaml
script: !include_dir_named scripts
shell_command: !include shellcmds.yaml
ffmpeg: 
camera: !include camera.yaml
rest_command: !include restcmd.yaml
feedreader:
  urls:
    - https://alerts.weather.gov/cap/wwaatmget.php?x=NCZ041&y=0
    - https://alerts.weather.gov/cap/wwaatmget.php?x=MIC125&y=0
  scan_interval:
   minutes: 30
panel_iframe: !include panels.yaml
image_processing:
  - platform: microsoft_vision
    api_key: 1b36f864bb8c42229e74febf891b31fa
    azure_region: eastus2
    services:
    - describe

