homeassistant: !include home.yaml
frontend:
hassio:
config:
history:
logger: !include logger.yaml
recorder: !include mysql.yaml
system_health:
sun:
ios:
panel_iframe: !include panels.yaml
emulated_hue: !include hue.yaml
mqtt: !include mqtt.yaml
device_tracker: !include device_trackers.yaml
zone: !include zones.yaml
input_select: !include select.yaml
input_text: !include input_text.yaml
input_boolean: !include input_boolean.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list sensors_binary
switch: !include_dir_merge_list switches
tplink: !include tplink.yaml
light: !include_dir_merge_list lights
notify: !include notify.yaml
person:
automation: !include automations.yaml
script: !include scripts.yaml
alert: !include alerts.yaml
zwave: !include zwave.yaml
climate: !include climate.yaml
ffmpeg: 
camera: !include camera.yaml
rest_command: !include restcmd.yaml
feedreader: !include weather_feed.yaml
google: !include calendar.yaml