- platform: google_maps
  username: !secret GENERIC_USER
  password: !secret GENERIC_PASS
- platform: tile
  username: !secret GENERIC_USER
  password: !secret GENERIC_PASS
- platform: nmap_tracker
  hosts: 192.168.101.100-150
  home_interval: 10
  scan_options: -F --host-timeout 5s -Pn