- !include forecast.yaml

- platform: template
  sensors: !include template_sensors.yaml

- platform: mqtt
  name: "ESP_1668C4_Temp"
  state_topic: "home/ESP_1668C4/temperature"

- platform: mqtt
  name: "ESP_1668C4_Humid"
  state_topic: "home/ESP_1668C4/humidity"

- platform: mqtt
  name: "ESP_1668C4_Dist"
  state_topic: "home/ESP_1668C4/distance"

- platform: mqtt
  name: "ESP_165A0C_Motion"
  state_topic: "home/ESP_165A0C/motion"

- platform: mqtt
  name: "Garage Door"
  state_topic: "home/garage/door"

- platform: mqtt
  name: "Deck Door"
  state_topic: "home/deck/door"

- platform: mqtt
  name: "Front Door"
  state_topic: "home/front/door"

- platform: mqtt
  name: "Back Door"
  state_topic: "home/back/door"

- platform: mqtt
  name: "Kitchen Temperature"
  state_topic: "home/kitchen/temperature"

- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "home/kitchen/humidity"

- platform: mqtt
  name: "Motion Family"
  state_topic: "home/motion/family"

- platform: mqtt
  name: "Motion Office"
  state_topic: "home/motion/office"

