- !include forecast.yaml

- platform: mqtt
  name: "Garage Door"
  state_topic: "home/garage/door"

- platform: mqtt
  name: "Deck Door"
  state_topic: "home/deck/door"

- platform: mqtt
  name: "Front Door"
  state_topic: "home/front/door"

- platform: mqtt
  name: "Back Door"
  state_topic: "home/back/door"

- platform: mqtt
  name: "Kitchen Temperature"
  state_topic: "home/kitchen/temperature"

- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "home/kitchen/humidity"

- platform: mqtt
  name: "Motion Family"
  state_topic: "home/motion/family"

- platform: mqtt
  name: "Motion Office"
  state_topic: "home/motion/office"

