- !include forecast.yaml

- platform: template
  sensors:
    cool1state:
      friendly_name: State1
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_2_2.attributes.operating_state }}'
      entity_id: 
        climate.trane_model_tzemt400bb32maa_cooling_1_2_2
    cool1mode:
      friendly_name: Mode1
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_2_2.attributes.operation_mode }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_2_2
    cool1fan:
      friendly_name: Fan1
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_2_2.attributes.fan_mode }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_2_2
    cool1target:
      friendly_name: Target1
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_2_2.attributes.temperature }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_2_2
    cool2state:
      friendly_name: State2
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_4_2.attributes.operating_state }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_4_2
    cool2mode:
      friendly_name: Mode2
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_4_2.attributes.operation_mode }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_4_2
    cool2fan:
      friendly_name: Fan2
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_4_2.attributes.fan_mode }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_4_2
    cool2target:
      friendly_name: Target2
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_4_2.attributes.temperature }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_4_2
    cool3state:
      friendly_name: State3
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_5_2.attributes.operating_state }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_5_2
    cool3mode:
      friendly_name: Mode3
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_5_2.attributes.operation_mode }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_5_2
    cool3fan:
      friendly_name: Fan3
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_5_2.attributes.fan_mode }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_5_2
    cool3target:
      friendly_name: Target3
      value_template: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_5_2.attributes.temperature }}'
      entity_id:
        climate.trane_model_tzemt400bb32maa_cooling_1_5_2

- platform: mqtt
  name: "Garage Door"
  state_topic: "home/garage/door"

- platform: mqtt
  name: "Deck Door"
  state_topic: "home/deck/door"

- platform: mqtt
  name: "Front Door"
  state_topic: "home/front/door"

- platform: mqtt
  name: "Back Door"
  state_topic: "home/back/door"

- platform: mqtt
  name: "Kitchen Temperature"
  state_topic: "home/kitchen/temperature"

- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "home/kitchen/humidity"

- platform: mqtt
  name: "Motion Family"
  state_topic: "home/motion/family"

- platform: mqtt
  name: "Motion Office"
  state_topic: "home/motion/office"

