- platform: rpi_gpio
  ports:
    11: HTPC
#    12: MODEM

- platform: dlink
  host: !secret DLINK_HOST
  name: dlink
  username: Admin
  password: !secret DLINK_KEY

- platform: template
  switches: !include template_switches.yaml

- platform: mqtt
  name: "ESP_1668C4_Relay"
  command_topic: "home/ESP_1668C4/relay/set"
  payload_on: "1"
  payload_off: "0"


