- platform: template
  sensors:
    ac2state:
      friendly_name: State2
      value_template: '{{ 
states.climate.trane2_cooling_1.attributes.operating_state }}'
      entity_id:
        climate.trane2_cooling_1
    ac2mode:
      friendly_name: Mode2
      value_template: '{{ 
states.climate.trane2_cooling_1.attributes.operation_mode }}'
      entity_id:
        climate.trane2_cooling_1
    ac2fan:
      friendly_name: Fan2
      value_template: '{{ 
states.climate.trane2_cooling_1.attributes.fan_mode }}'
      entity_id:
        climate.trane2_cooling_1
    ac2cool:
      friendly_name: CoolTarget2
      value_template: '{{ 
states.climate.trane2_cooling_1.attributes.temperature }}'
      entity_id:
        climate.trane2_cooling_1
    ac2heat:
      friendly_name: HeatTarget2
      value_template: '{{ 
states.climate.trane2_heating_1.attributes.temperature }}'
      entity_id:
        climate.trane2_heating_1
