- platform: template
  sensors:
    cool2state:
      friendly_name: State2
      value_template: '{{ states.climate.trane2_cooling_1.attributes.operating_state }}'
      entity_id:
        climate.trane2_cooling_1
    ac2mode:
      friendly_name: Mode2
      value_template: '{{ states.climate.trane2_cooling_1.attributes.operation_mode }}'
      entity_id:
        climate.trane2_cooling_1
    cool2fan:
      friendly_name: Fan2
      value_template: '{{ states.climate.trane2_cooling_1.attributes.fan_mode }}'
      entity_id:
        climate.trane2_cooling_1
    cool2target:
      friendly_name: CoolTarget2
      value_template: '{{ states.climate.trane2_cooling_1.attributes.temperature }}'
      entity_id:
        climate.trane2_cooling_1
    heat2target:
      friendly_name: HeatTarget2
      value_template: '{{ states.climate.trane2_heating_1.attributes.temperature }}'
      entity_id:
        climate.trane2_heating_1