- platform: mqtt
  name: 'esp_1668C4_distance'
  state_topic: 'home/ESP_1668C4/distance'
  expire_after: 60
- platform: mqtt
  name: 'esp_1668C4_relay'
  state_topic: 'home/ESP_1668C4/relay1'
  expire_after: 60
- platform: mqtt
  name: 'esp_90B322_relay'
  state_topic: 'home/ESP_90B322/relay'
  expire_after: 60
- platform: mqtt
  name: 'esp_90B322_relay2'
  state_topic: 'home/ESP_90B322/relay2'
  expire_after: 60
- platform: mqtt
  name: 'esp_90B322_motion'
  state_topic: 'home/ESP_90B322/motion'