- platform: mqtt
  name: 'ESP_1668C4_Dist'
  state_topic: 'home/ESP_1668C4/distanceMedian'
  expire_after: 60
- platform: mqtt
  name: 'ESP_1668C4_Relay'
  state_topic: 'home/ESP_1668C4/relay'
  expire_after: 60
  state_on: '1'
  state_off: '0'
- platform: mqtt
  name: 'ESP_90B322_Relay'
  state_topic: 'home/ESP_90B322/relay'
  state_on: 'ON'
  state_off: 'OFF'
  expire_after: 60
- platform: mqtt
  name: 'ESP_90B322_Relay2'
  state_topic: 'home/ESP_90B322/relay2'
  state_on: 'ON'
  state_off: 'OFF'
  expire_after: 60
- platform: mqtt
  name: 'ESP_90B322_Motion'
  state_topic: 'home/ESP_90B322/motion'
  state_on: 'ON'
  state_off: 'OFF'
