alias: ac2 cool target selected
trigger:
  platform: state
  entity_id: input_select.cool2target
condition:
  condition: template
  value_template: '{{ states.input_select.cool2target.state != states.climate.trane_model_tzemt400bb32maa_cooling_1_4_2.attributes.temperature }}'
action:
  service: climate.set_temperature
  entity_id: climate.trane_model_tzemt400bb32maa_cooling_1_4_2
  data_template:
    temperature: "{{ states('input_select.cool2target') }}"
