alias: ac2_cooltemp
trigger:
  platform: state
  entity_id: climate.trane2_cooling_1
condition:
  condition: state
  entity_id: input_boolean.hass_booting
  state: 'off'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.cool2target
    data_template:
      option: '{{ states.climate.trane2_cooling_1.attributes.temperature }}'
