alias: ac2 cool target selected
trigger:
  platform: state
  entity_id: input_select.cool2target
condition:
  condition: state
  entity_id: input_boolean.hass_booting
  state: 'off'
action:
  service: climate.set_temperature
  entity_id: climate.trane2_cooling_1
  data_template:
    temperature: "{{ states('input_select.cool2target') }}"
