alias: ac3 change on cool temp
trigger:
  platform: state
  entity_id: climate.trane_model_tzemt400bb32maa_cooling_1_5_2
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.cool3target
    data_template:
      option: '{{ states.climate.trane_model_tzemt400bb32maa_cooling_1_5_2.attributes.temperature }}'
