alias: ac3 change on heat temp
trigger:
  platform: state
  entity_id: climate.trane3_heating_1
condition:
  condition: state
  entity_id: input_boolean.hass_booting
  state: 'off'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.heat3target
    data_template:
      option: '{{ states.climate.trane3_heating_1.attributes.temperature }}'
