alias: ac3 heat target selected
trigger:
  platform: state
  entity_id: input_select.heat3target
condition:
  condition: state
  entity_id: input_boolean.hass_booting
  state: 'off'
action:
  service: climate.set_temperature
  entity_id: climate.trane3_heating_1
  data_template:
    temperature: "{{ states('input_select.heat3target') }}"
