alias: Hass started
trigger:
  platform: homeassistant
  event: start
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.hass_booting
  - service: mqtt.publish
    data:
      topic: 'home/status'
  - delay:
      seconds: 150
  - service: input_select.select_option
    data:
      entity_id: input_select.cool1target
    data_template:
      option: '{{ states.climate.trane1_cooling_1.attributes.temperature }}'
  - service: input_select.select_option
    data:
      entity_id: input_select.cool2target
    data_template:
      option: '{{ states.climate.trane2_cooling_1.attributes.temperature }}'
  - service: input_select.select_option
    data:
      entity_id: input_select.cool3target
    data_template:
      option: '{{ states.climate.trane3_cooling_1.attributes.temperature }}'
  - service: input_select.select_option
    data:
      entity_id: input_select.heat1target
    data_template:
      option: '{{ states.climate.trane1_heating_1.attributes.temperature }}'
  - service: input_select.select_option
    data:
      entity_id: input_select.heat2target
    data_template:
      option: '{{ states.climate.trane2_heating_1.attributes.temperature }}'
  - service: input_select.select_option
    data:
      entity_id: input_select.heat3target
    data_template:
      option: '{{ states.climate.trane3_heating_1.attributes.temperature }}'
  - delay:
      seconds: 15
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.hass_booting

